### ISSUE TITLE
Day period is undefined

### ISSUE THREAD

**Issue by ccpu** [zapier/intl-dateformat#4]
Apparently using the 'A' for day period is not working, it will display undefined.

Repruduced probelem:
[https://codesandbox.io/s/relaxed-raman-ze0qk](https://codesandbox.io/s/relaxed-raman-ze0qk)

Thanks,

**Comment by ngryman** [comment]
Thanks for the report!

`intl-dateformat` was using the lowercase version of the parsed day period (`dayperiod`). This was actually a bug in Chrome < 71 and Node 10 on which the library was tested. Since then they fixed the issue and switched to the standard camelcase version (`dayPeriod`).

I fixed the issue by supporting both cases and published a new [v0.1.1](https://github.com/zapier/intl-dateformat/releases/tag/v0.1.1) version.

Let me know if you have other issues. Thanks!
